#ifndef DEBUG_H

#define DEBUG_H

#define DEBUG_CLIENT_CONNECTION 1
#define DEBUG_PRINT_RECEIVED_MESSAGE 1
#define DEBUG_PRINT_SENT_MESSAGE 1
#define DEBUG_PRINT_AUTHENTICATION 0
#define DEBUG_PRINT_NICKNAME 0
#define DEBUG_PRINT_USER_REAL_NAME 0
#define DEBUG_PING_CLIENT 0
#define DEBUG_PRINT_CLIENT_QUIT 0

#endif /* end of include guard: DEBUG_H */
