#ifndef DEBUG_H

#define DEBUG_H

#define DEBUG_CLIENT_CONNECTION 1
#define DEBUG_PRINT_RECEIVED_MESSAGE 1
#define DEBUG_PRINT_SENT_MESSAGE 1
#define DEBUG_PRINT_AUTHENTICATION 1

#endif /* end of include guard: DEBUG_H */
